# Generated by Django 5.0 on 2024-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorylogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categorylogo/')),
            ],
        ),
    ]
